# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "suruoxi"
repo_name: "HumanAIGC-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
black_list_path: 'blacklists.txt'
recent_trend_path: './pdf_analysis/recent_trends.txt'
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
claudeai_path: 'analysis_by_ai.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Talking Face": 
        filters: ["Talking Face", "Talking Head", "Talking Avatar",  "Animate Portrait", "Visual Dubbing", "Face Genertation", "Lip Sync", "Talker", "Talking Video",  "Face Reenactment", "Wav2lip", "Lip Generation", "Lip Synchronization", "Portrait Animation", "Facial Animation", "Lip Expert"]
    "Image Animation":
        filters: ["Image Animator", "Image Animation"]
    "Video Generation":
        filters: ["Video Generation", "Video Synthesis", "Long Video Generation"]
    "TryOn":
        filters: ["Try on", "tryon", "virtual tryon"]
    "Music2Dance and Co-speech":
        filters: ["Music2Dance", "Music Dance", "Co-Speech", "Co-Speech Video", "Human motion", "dance video"]
    "Visual Edit":
        filters: ["image edit", "video edit", "visual edit"]
    "Speech and Interaction":
        filters: ["TTS", "Text to speech", "Speech Synthesis", "Voice Synthesis", "Speech Generation", "Neural Speech Synthesis", "Neural TTS", "dialogue", "voice interaction", "multimodal interaction",]
    "Others":
        filters: ["training-free","Vision-Language-Action", "Real time generation", "real time", "Video Personalization","Multimodal generation", "audio-video", "audio-visual"]
    "Post Training":
        filters: ["DPO", "REFL", "RLHF", "Reward Feedback Learning", "reinforcement learning from human feedback", "GRPO", "Reinforcelearning", "Video Alignment", "human video alignment"]
